-- Create the db on the postgres service-db, then reopen the connection to the actual db
CREATE DATABASE "HeatingDataMonitor";

-- With the help of https://github.com/dotnet/efcore/issues/5096#issuecomment-326045537
CREATE TABLE "HeatingData" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Zeit" timestamp without time zone NOT NULL,
    "Kessel" real NULL,
    "Ruecklauf" real NULL,
    "Abgas" real NULL,
    "Brennkammer" real NULL,
    "CO2_Soll" real NULL,
    "CO2_Ist" real NULL,
    "Saugzug_Ist" real NULL,
    "Puffer_Oben" real NULL,
    "Puffer_Unten" real NULL,
    "Platine" real NULL,
    "Betriebsphase_Kessel" integer NULL,
    "Aussen" real NULL,
    "Vorlauf_HK1_Ist" real NULL,
    "Vorlauf_HK1_Soll" real NULL,
    "Betriebsphase_HK1" integer NULL,
    "Betriebsart_Fern_HK1" integer NULL,
    "Verschiebung_Fern_HK1" real NULL,
    "Freigabekontakt_HK1" real NULL,
    "Vorlauf_HK2_Ist" real NULL,
    "Vorlauf_HK2_Soll" real NULL,
    "Betriebsphase_HK2" integer NULL,
    "Betriebsart_Fern_HK2" integer NULL,
    "Verschiebung_Fern_HK2" real NULL,
    "Freigabekontakt_HK2" real NULL,
    "Vorlauf_HK3_Ist" real NULL,
    "Vorlauf_HK3_Soll" real NULL,
    "Betriebsphase_HK3" integer NULL,
    "Betriebsart_Fern_HK3" integer NULL,
    "Verschiebung_Fern_HK3" real NULL,
    "Freigabekontakt_HK3" real NULL,
    "Vorlauf_HK4_Ist" real NULL,
    "Vorlauf_HK4_Soll" real NULL,
    "Betriebsphase_HK4" integer NULL,
    "Betriebsart_Fern_HK4" integer NULL,
    "Verschiebung_Fern_HK4" real NULL,
    "Freigabekontakt_HK4" real NULL,
    "Boiler_1" real NULL,
    "Boiler_2" real NULL,
    "DI_0" integer NULL,
    "DI_1" integer NULL,
    "DI_2" integer NULL,
    "DI_3" integer NULL,
    "A_W_0" integer NULL,
    "A_W_1" integer NULL,
    "A_W_2" integer NULL,
    "A_W_3" integer NULL,
    "A_EA_0" integer NULL,
    "A_EA_1" integer NULL,
    "A_EA_2" integer NULL,
    "A_EA_3" integer NULL,
    "A_EA_4" integer NULL,
    "A_PHASE_0" integer NULL,
    "A_PHASE_1" integer NULL,
    "A_PHASE_2" integer NULL,
    "A_PHASE_3" integer NULL,
    "A_PHASE_4" integer NULL,
    CONSTRAINT "PK_HeatingData" PRIMARY KEY ("Id")
);

-- Hopefully that's good
CREATE INDEX "IX_HeatingData_Zeit" ON "HeatingData" ("Zeit");


CREATE ROLE "heatingDataMonitorRole" WITH
	NOLOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;

REVOKE ALL ON ALL TABLES IN SCHEMA public from "heatingDataMonitorRole";
GRANT SELECT, INSERT on "HeatingData" to "heatingDataMonitorRole";

CREATE ROLE "heatingDataMonitorUser" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'dontworrythispasswordwillchangeinproduction';
	
GRANT "heatingDataMonitorRole" TO "heatingDataMonitorUser";
