-- Create the db on the postgres service-db, then reopen the connection to the actual db
CREATE DATABASE heating_data_monitor;

-- With the help of https://github.com/dotnet/efcore/issues/5096#issuecomment-326045537
CREATE TABLE heating_data (
    sps_zeit timestamp without time zone NOT NULL,
    received_time timestamp without time zone NOT NULL,
    kessel real NULL,
    ruecklauf real NULL,
    abgas real NULL,
    brennkammer real NULL,
    co2_soll real NULL,
    co2_ist real NULL,
    saugzug_ist real NULL,
    puffer_oben real NULL,
    puffer_unten real NULL,
    platine real NULL,
    betriebsphase_kessel integer NULL,
    aussen real NULL,
    vorlauf_hk1_ist real NULL,
    vorlauf_hk1_soll real NULL,
    betriebsphase_hk1 integer NULL,
    betriebsart_fern_hk1 integer NULL,
    verschiebung_fern_hk1 real NULL,
    freigabekontakt_hk1 real NULL,
    vorlauf_hk2_ist real NULL,
    vorlauf_hk2_soll real NULL,
    betriebsphase_hk2 integer NULL,
    betriebsart_fern_hk2 integer NULL,
    verschiebung_fern_hk2 real NULL,
    freigabekontakt_hk2 real NULL,
    vorlauf_hk3_ist real NULL,
    vorlauf_hk3_soll real NULL,
    betriebsphase_hk3 integer NULL,
    betriebsart_fern_hk3 integer NULL,
    verschiebung_fern_hk3 real NULL,
    freigabekontakt_hk3 real NULL,
    vorlauf_hk4_ist real NULL,
    vorlauf_hk4_soll real NULL,
    betriebsphase_hk4 integer NULL,
    betriebsart_fern_hk4 integer NULL,
    verschiebung_fern_hk4 real NULL,
    freigabekontakt_hk4 real NULL,
    boiler_1 real NULL,
    boiler_2 real NULL,
    di_0 integer NULL,
    di_1 integer NULL,
    di_2 integer NULL,
    di_3 integer NULL,
    a_w_0 integer NULL,
    a_w_1 integer NULL,
    a_w_2 integer NULL,
    a_w_3 integer NULL,
    a_ea_0 integer NULL,
    a_ea_1 integer NULL,
    a_ea_2 integer NULL,
    a_ea_3 integer NULL,
    a_ea_4 integer NULL,
    a_phase_0 integer NULL,
    a_phase_1 integer NULL,
    a_phase_2 integer NULL,
    a_phase_3 integer NULL,
    a_phase_4 integer NULL
);

-- CREATE INDEX ix_heating_data_received_time ON heating_data (received_time) INCLUDE (kessel, puffer_oben, puffer_unten, boiler_1);

SELECT create_hypertable('heating_data', 'received_time');
