import { BetriebsPhaseHK } from './betriebsphase-hk.enum';
import { BetriebsPhaseKessel } from './betriebsphase-kessel.enum';

export interface HeatingData {
    SPS_Zeit: string;
    ReceivedTime: string;
    Kessel: number;
    Ruecklauf: number;
    Abgas: number;
    CO2_Soll: number;
    CO2_Ist: number;
    Saugzug_Ist: number;
    Puffer_Oben: number;
    Puffer_Unten: number;
    Platine: number;
    Betriebsphase_Kessel: BetriebsPhaseKessel;
    Aussen: number;
    Vorlauf_HK1_Ist: number;
    Vorlauf_HK1_Soll: number;
    Betriebsphase_HK1: BetriebsPhaseHK;
    Vorlauf_HK2_Ist: number;
    Vorlauf_HK2_Soll: number;
    Betriebsphase_HK2: BetriebsPhaseHK;
    Boiler_1: number;
    DI_0: boolean;
    DI_1: boolean;
    DI_2: boolean;
    DI_3: boolean;
    A_W_0: boolean;
    A_W_1: boolean;
    A_W_2: boolean;
    A_W_3: boolean;
    A_EA_0: boolean;
    A_EA_1: boolean;
    A_EA_2: boolean;
    A_EA_3: boolean;
    A_EA_4: boolean;
    A_PHASE_0: boolean;
    A_PHASE_1: boolean;
    A_PHASE_2: boolean;
    A_PHASE_3: boolean;
    A_PHASE_4: boolean;
}
